/// Country name aliases keyed by uppercase ISO-3166-1 alpha-2 code.
/// Translated from the Go `RORCountries` map in ror/matching.go.
/// All alias strings are lowercase; 2-letter entries are matched as isolated tokens.
pub static ROR_COUNTRIES: &[(&str, &[&str])] = &[
    ("AD", &["andorra"]),
    (
        "AE",
        &[
            "al imarat al arabiyah al muttahidah",
            "arab emirates",
            "uae",
            "united arab emirates",
        ],
    ),
    ("AF", &["afghanestan", "afghanistan"]),
    ("AG", &["antigua", "antigua and barbuda", "barbuda"]),
    ("AI", &["anguilla"]),
    ("AL", &["albania", "shqiperia"]),
    ("AM", &["armenia", "hayastan"]),
    ("AN", &["netherlands antilles"]),
    ("AO", &["angola"]),
    ("AQ", &["antarctica"]),
    ("AR", &["ar", "argentina", "argentine"]),
    ("AS", &["american samoa"]),
    ("AT", &["austria", "aut", "oesterreich", "osterreich"]),
    ("AU", &["au", "aus", "australia"]),
    ("AW", &["aruba"]),
    ("AX", &["aland islands"]),
    ("AZ", &["azarbaycan respublikasi", "aze", "azerbaijan"]),
    (
        "BA",
        &[
            "bosna i hercegovina",
            "bosnia",
            "bosnia and herzegovina",
            "herzegovina",
        ],
    ),
    ("BB", &["barbados"]),
    ("BD", &["bangladesh"]),
    ("BE", &["bel", "belgie", "belgique", "belgium"]),
    ("BF", &["bfa", "burkina faso"]),
    ("BG", &["bulariya", "bulgaria", "republika bulgariya"]),
    ("BH", &["al bahrayn", "bahrain"]),
    ("BI", &["burundi"]),
    ("BJ", &["ben", "benin"]),
    ("BL", &["saint barthelemy"]),
    ("BM", &["bermuda"]),
    ("BN", &["brunei", "brunei darussalam"]),
    ("BO", &["bolivia"]),
    ("BQ", &["bonaire", "bonaire, sint eustatius and saba"]),
    ("BR", &["br", "bra", "brasil", "brazil"]),
    ("BS", &["bahamas", "the bahamas"]),
    ("BT", &["bhutan", "drukyul"]),
    ("BV", &["bouvet island"]),
    ("BW", &["botswana"]),
    ("BY", &["belarus", "byelarus"]),
    ("BZ", &["belice", "belize"]),
    ("CA", &["ca", "can", "canada"]),
    ("CC", &["cocos islands", "keeling islands"]),
    (
        "CF",
        &["central african republic", "republique centrafricaine"],
    ),
    (
        "CG",
        &[
            "congo",
            "democratic republic of the congo",
            "republic of the congo",
            "republique democratique du congo",
            "republique du congo",
        ],
    ),
    (
        "CH",
        &["che", "schweiz", "suisse", "svizzera", "switzerland"],
    ),
    ("CI", &["cote d'ivoire"]),
    ("CK", &["cook islands"]),
    ("CL", &["chile"]),
    ("CM", &["cameroon", "cameroun"]),
    (
        "CN",
        &[
            "china",
            "china (people's republic of)",
            "chn",
            "cn",
            "people's republic of china",
            "p r china",
            "p. r. china",
            "pr china",
            "republic of china",
            "r. o. c.",
            "zhong guo",
        ],
    ),
    ("CO", &["col", "colombia"]),
    ("CR", &["costa rica", "cri"]),
    ("CU", &["cuba"]),
    ("CV", &["cabo verde", "cape verde"]),
    ("CW", &["curacao"]),
    ("CX", &["christmas island"]),
    ("CY", &["cyprus", "kibris", "kypros"]),
    ("CZ", &["ceska republika", "cze", "czech republic"]),
    (
        "DE",
        &[
            "de",
            "deu",
            "deutschland",
            "federal republic of germany",
            "germany",
        ],
    ),
    ("DJ", &["djibouti"]),
    ("DK", &["danmark", "denmark", "dnk"]),
    ("DM", &["dominica"]),
    ("DO", &["dominican republic", "republica dominicana"]),
    ("DZ", &["algeria", "al jaza'ir"]),
    ("EC", &["ecuador"]),
    ("EE", &["eesti", "est", "estonia"]),
    ("EG", &["egypt", "misr"]),
    ("EH", &["western sahara"]),
    ("ER", &["eritrea", "ertra"]),
    ("ES", &["esp", "espana", "spain"]),
    ("ET", &["ethiopia", "yeityop'iya"]),
    ("EU", &["eec"]),
    ("FI", &["fin", "finland", "suomi"]),
    ("FJ", &["fiji"]),
    ("FK", &["falkland islands"]),
    ("FM", &["federated states of micronesia", "micronesia"]),
    ("FO", &["faroe islands"]),
    ("FR", &["fr", "fra", "france", "republique francaise"]),
    ("GA", &["gabon"]),
    ("GD", &["grenada"]),
    ("GE", &["georgia", "sak'art'velo"]),
    ("GF", &["french guiana"]),
    ("GG", &["guernsey"]),
    ("GH", &["ghana"]),
    ("GI", &["gibraltar"]),
    ("GL", &["greenland"]),
    ("GM", &["gambia"]),
    ("GN", &["guinea", "guinea ecuatorial", "guinee"]),
    ("GP", &["guadeloupe"]),
    ("GQ", &["equatorial guinea"]),
    ("GR", &["ellas", "grc", "greece"]),
    ("GS", &["south georgia"]),
    ("GT", &["guatemala"]),
    ("GU", &["guam"]),
    ("GW", &["guinea-bissau", "guine-bissau"]),
    ("GY", &["guyana"]),
    ("HK", &["hong kong"]),
    (
        "HM",
        &[
            "heard island",
            "heard island and mcdonald islands",
            "mcdonald islands",
        ],
    ),
    ("HN", &["honduras"]),
    ("HR", &["croatia", "hrvatska"]),
    ("HT", &["haiti"]),
    ("HU", &["hun", "hungary", "magyarorszag"]),
    ("ID", &["idn", "indonesia"]),
    ("IE", &["eire", "ireland", "irl"]),
    ("IL", &["isr", "israel", "yisra'el"]),
    ("IM", &["isle of man"]),
    ("IN", &["bharat", "ind", "india"]),
    ("IO", &["british indian ocean territory"]),
    ("IQ", &["al iraq", "iraq"]),
    ("IR", &["iran", "persia"]),
    ("IS", &["iceland", "isl", "island"]),
    ("IT", &["ita", "italia", "italy"]),
    ("JE", &["jersey"]),
    ("JM", &["jamaica"]),
    ("JO", &["al urdun", "jordan"]),
    ("JP", &["japan", "jpn", "nippon", "tokyo"]),
    ("KE", &["kenya"]),
    ("KG", &["kyrgyz respublikasy", "kyrgyzstan"]),
    ("KH", &["cambodia", "kampuchea"]),
    ("KI", &["kiribati"]),
    ("KM", &["comores", "comoros"]),
    ("KN", &["nevis", "saint kitts", "saint kitts and nevis"]),
    ("KO", &["kosova", "kosovo"]),
    (
        "KP",
        &["choson", "choson-minjujuui-inmin-konghwaguk", "north korea"],
    ),
    (
        "KR",
        &[
            "kor",
            "korea",
            "republic of korea",
            "korea (republic of)",
            "south korea",
            "taehan-min'guk",
        ],
    ),
    ("KW", &["al kuwayt", "kuwait"]),
    ("KY", &["cayman islands"]),
    ("KZ", &["kazakhstan", "qazaqstan"]),
    (
        "LA",
        &[
            "lao (people's democratic republic)",
            "lao people's democratic republic",
            "laos",
            "sathalanalat paxathipatai paxaxon lao",
        ],
    ),
    ("LB", &["lebanon", "lubnan"]),
    ("LC", &["saint lucia"]),
    ("LI", &["liechtenstein"]),
    ("LK", &["sri lanka"]),
    ("LR", &["liberia"]),
    ("LS", &["lesotho"]),
    ("LT", &["lietuva", "lithuania", "ltu"]),
    ("LU", &["lux", "luxembourg"]),
    ("LV", &["latvia", "latvija"]),
    ("LY", &["libya", "libyan arab jamahiriya"]),
    ("MA", &["al maghrib", "morocco"]),
    ("MC", &["monaco"]),
    (
        "MD",
        &["moldova", "moldova (republic of)", "republic of moldova"],
    ),
    ("ME", &["montenegro"]),
    ("MF", &["saint martin", "saint martin (french part)"]),
    ("MG", &["madagascar"]),
    ("MH", &["marshall islands"]),
    (
        "MK",
        &[
            "federal republic of yugoslavia",
            "former yugoslav republic of macedonia",
            "macedonia",
            "makedonija",
            "yugoslavia",
        ],
    ),
    ("ML", &["mali"]),
    ("MM", &["burma", "myanma naingngandaw", "myanmar"]),
    ("MN", &["mongolia", "mongol uls"]),
    ("MO", &["macao"]),
    ("MP", &["northern mariana islands"]),
    ("MQ", &["martinique"]),
    ("MR", &["mauritania", "muritaniyah"]),
    ("MS", &["montserrat"]),
    ("MT", &["malta"]),
    ("MU", &["mauritius"]),
    ("MV", &["dhivehi raajje", "maldives"]),
    ("MW", &["malawi"]),
    ("MX", &["mex", "mexico"]),
    ("MY", &["malaysia"]),
    ("MZ", &["mocambique", "mozambique"]),
    ("NA", &["namibia"]),
    ("NC", &["new caledonia"]),
    ("NE", &["niger"]),
    ("NF", &["norfolk island"]),
    ("NG", &["nigeria"]),
    ("NI", &["nicaragua"]),
    (
        "NL",
        &["nederland", "netherlands", "nl", "nld", "the netherlands"],
    ),
    ("NO", &["nor", "norge", "norway"]),
    ("NP", &["nepal"]),
    ("NR", &["nauru"]),
    ("NU", &["niue"]),
    ("NZ", &["new zealand", "nzl"]),
    ("OM", &["oman", "uman"]),
    ("PA", &["pan", "panama"]),
    ("PE", &["peru"]),
    ("PF", &["french polynesia", "pyf"]),
    ("PG", &["papua new guinea"]),
    ("PH", &["philippines", "pilipinas"]),
    ("PK", &["pakistan"]),
    ("PL", &["pol", "poland", "polska"]),
    (
        "PM",
        &["miquelon", "saint pierre", "saint pierre and miquelon"],
    ),
    ("PN", &["pitcairn"]),
    ("PR", &["puerto rico"]),
    ("PS", &["palestine"]),
    ("PT", &["portugal"]),
    ("PW", &["palau"]),
    ("PY", &["paraguay"]),
    ("QA", &["qatar"]),
    ("RE", &["reunion"]),
    ("RO", &["romania", "rou"]),
    ("RS", &["serbia", "srbija-crna gora"]),
    ("RU", &["rossiya", "rus", "russia", "russian federation"]),
    ("RW", &["rwanda"]),
    ("SA", &["al arabiyah as suudiyah", "saudi arabia"]),
    ("SB", &["solomon islands"]),
    ("SC", &["seychelles"]),
    ("SD", &["as-sudan", "sudan"]),
    ("SE", &["sverige", "swe", "sweden"]),
    ("SG", &["sgp", "singapore"]),
    ("SH", &["saint helena"]),
    ("SI", &["slovenia", "slovenija", "svn"]),
    ("SJ", &["jan mayen", "svalbard"]),
    ("SK", &["slovakia", "slovensko", "svk"]),
    ("SL", &["sierra leone"]),
    ("SM", &["san marino"]),
    ("SN", &["sen", "senegal"]),
    ("SO", &["somalia"]),
    ("SR", &["suriname"]),
    ("SS", &["south sudan"]),
    (
        "ST",
        &[
            "principe",
            "sao tome",
            "sao tome and principe",
            "sao tome e principe",
        ],
    ),
    ("SV", &["el salvador", "slv"]),
    ("SX", &["sint maarten"]),
    ("SY", &["suriyah", "syria", "syrian arab republic"]),
    ("SZ", &["swaziland"]),
    (
        "TC",
        &["caicos islands", "turks", "turks and caicos islands"],
    ),
    ("TD", &["chad", "tchad"]),
    ("TF", &["french southern territories"]),
    ("TG", &["togo"]),
    ("TH", &["muang thai", "thailand"]),
    ("TJ", &["jumhurii tojikistan", "tajikistan"]),
    ("TK", &["tokelau"]),
    ("TL", &["timor-leste"]),
    ("TM", &["turkmenistan"]),
    ("TN", &["tunisia"]),
    ("TO", &["tonga"]),
    ("TR", &["tur", "turkey", "turkiye"]),
    ("TT", &["tobago", "trinidad", "trinidad and tobago"]),
    ("TV", &["tuvalu"]),
    ("TW", &["taiwan", "t'ai-wan", "taiwan r.o.c", "twn"]),
    ("TZ", &["tanzania", "tanzania (united republic of)"]),
    ("UA", &["ukr", "ukraine", "ukrayina"]),
    ("UG", &["uganda"]),
    (
        "UK",
        &[
            "gb",
            "gbr",
            "great britain",
            "northern ireland",
            "london",
            "scotland",
            "uk",
            "u. k.",
            "u.k.",
            "u. k",
            "u.k",
            "united kingdom",
        ],
    ),
    ("UM", &["united states minor outlying islands"]),
    (
        "US",
        &[
            "ak",
            "al",
            "alabama",
            "alaska",
            "ar",
            "arizona",
            "arkansas",
            "az",
            "ca",
            "california",
            "co",
            "colorado",
            "connecticut",
            "ct",
            "de",
            "delaware",
            "fl",
            "florida",
            "ga",
            "georgia",
            "hawaii",
            "hi",
            "ia",
            "id",
            "idaho",
            "il",
            "ill",
            "illinois",
            "in",
            "indiana",
            "iowa",
            "kansas",
            "kentucky",
            "ks",
            "ky",
            "la",
            "louisiana",
            "ma",
            "maine",
            "maryland",
            "massachusetts",
            "me",
            "mi",
            "michigan",
            "minnesota",
            "mississippi",
            "missouri",
            "mn",
            "mo",
            "montana",
            "ms",
            "mt",
            "nc",
            "nd",
            "ne",
            "nebraska",
            "nevada",
            "new hampshire",
            "new jersey",
            "new mexico",
            "new york",
            "nh",
            "nj",
            "nm",
            "north carolina",
            "north dakota",
            "nv",
            "ny",
            "oh",
            "ohio",
            "ok",
            "okla",
            "oklahoma",
            "or",
            "oregon",
            "pa",
            "pennsylvania",
            "rhode island",
            "ri",
            "sc",
            "sd",
            "south carolina",
            "south dakota",
            "tennessee",
            "texas",
            "tn",
            "tx",
            "united states",
            "united states of america",
            "us",
            "u. s.",
            "u.s.",
            "u. s",
            "u.s",
            "usa",
            "u. s. a.",
            "u.s.a.",
            "ut",
            "utah",
            "va",
            "vermont",
            "virginia",
            "vt",
            "wa",
            "washington",
            "west virginia",
            "wi",
            "wisconsin",
            "wv",
            "wy",
            "wyoming",
        ],
    ),
    ("UY", &["uruguay"]),
    ("UZ", &["uzbekistan", "uzbekiston respublikasi"]),
    (
        "VA",
        &[
            "citta del vaticano",
            "holy see",
            "santa sede",
            "vatican",
            "vatican city",
        ],
    ),
    (
        "VC",
        &[
            "saint vincent",
            "saint vincent and the grenadines",
            "the grenadines",
        ],
    ),
    ("VE", &["venezuela"]),
    ("VG", &["virgin islands"]),
    ("VN", &["vietnam", "viet nam"]),
    ("VU", &["vanuatu"]),
    ("WF", &["futuna", "wallis", "wallis and futuna"]),
    ("WS", &["samoa"]),
    ("YE", &["al yaman", "yemen"]),
    ("YT", &["mayotte"]),
    ("ZA", &["south africa", "zaf"]),
    ("ZM", &["zambia"]),
    ("ZW", &["zimbabwe"]),
];
